apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-deploy-binding
  namespace: githubrepo  
subjects:
- kind: ServiceAccount
  name: githubrepo
  namespace: githubrepo
roleRef:
  kind: Role
  name: edit  
  apiGroup: rbac.authorization.k8s.io
